[versions]
#plugins
kotlin = "1.9.10"
gradle = "8.1.1"

# Compose
compose = "1.5.3"
compose-ui = "1.5.1"
compose-bom = "2023.03.00"
compose-activity = "1.7.2"
compose-lifecycle = "2.6.1"
compose-material3 = "1.1.1"
compose-navigation = "2.7.1"
compose-preview = "1.5.1"
compose-coil = "2.4.0"
accompanist = "0.27.0"
onebone-toolbar = "2.3.2"
zoomable = "1.5.1"
# Android
android-lifecycle-ktx = "2.6.1"

#Ui/Unit test
junit = "4.12"
junit-ext-ktx = "1.1.5"
testing = "6.9.6"
#Network
retrofit = "2.9.0"
okkhttp = "4.11.0"

[libraries]
compose-ui = { group = "androidx.compose", name = "ui:ui", version.ref = "compose" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-ui" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-ui" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-material1 = {group = "androidx.compose.material", name = "material", version.ref = "compose-ui"}
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-ui" }
compose-accomponist = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-preview" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-preview" }
compose-coil = {group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil"}
compose-icons = {group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-ui"}
onebone-toolbar = {group = "me.onebone", name = "toolbar-compose", version.ref = "onebone-toolbar"}
android-lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "android-lifecycle-ktx" }
zoomable = {group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable"}

junit = {group = "junit", name = "junit",version.ref = "junit"}
junit-ext-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit-ext-ktx" }
testing = { group = "org.testng", name = "testing", version.ref = "testing" }

retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
okkhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okkhttp"}
okkhttp-interceptor = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref ="okkhttp"}

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = {id = "kotlin-parcelize", version.ref = "kotlin"}

[bundles]
composeUiBundle = [
    "compose-graphics",
    "compose-runtime",
    "compose-lifecycle-viewmodel",
    "compose-activity",
    "compose-material3",
    "compose-material1",
    "compose-navigation",
    "compose-accomponist",
    "android-lifecycle-ktx",
    "compose-coil",
    "compose-icons"
]
composeUiTest = ["junit-ext-ktx", "testing"]
composeUiBundleDebug = [
    "compose-preview",
    "compose-tooling-preview",
]
retrofit = ["retrofit", "retrofit-converter"]
okkhttp = ["okkhttp", "okkhttp-interceptor"]
network = ["retrofit", "retrofit-converter", "okkhttp", "okkhttp-interceptor"]

