name: Generated APK AAB (Upload - Create Artifact To Github Action)

on:
  push:
    branches:
      - NK/03-migrate-kmp

jobs:
  build:
    name: Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Decode and save keystore
      - name: Decode keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo "$KEYSTORE_FILE" | base64 -d > waifupics-key-store.key

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'

      # Extract version number from build.gradle
      - name: Extract version number
        id: version
        run: |
          VERSION_NAME=$(grep "versionName" modules/instances/app/build.gradle | awk '{print $2}' | tr -d '"')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # Build the APK
      - name: Build APK
        run: ./gradlew :modules:instances:app:assembleRelease --stacktrace

      # Find APK file
      - name: Find APK file
        id: apk
        run: |
          APK_PATH=$(find modules/instances/app/release/ -name "app-release.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "Error: APK not found!" && exit 1
          fi
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      # Sign the APK
      - name: Sign APK
        run: |
          jarsigner -verbose \
            -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore waifupics-key-store.key \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            $APK_PATH \
            ${{ secrets.KEY_ALIAS }}

      # Align the APK
      - name: Align APK
        run: |
          zipalign -v -p 4 $APK_PATH waifupics-${{ env.VERSION_NAME }}.apk

      # Upload the APK as a release artifact
      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: waifupics-${{ env.VERSION_NAME }}.apk
          asset_name: waifupics-${{ env.VERSION_NAME }}.apk
          content_type: application/vnd.android.package-archive

