name: Deploy Compose Web App (JS)

on:
  push:
    branches:
      - NK/03-migrate-kmp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: ./gradlew --no-daemon

      - name: Build distributable
        run: ./gradlew jsBrowserDistribution

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: modules/instances/web/build/dist/js/productionExecutable